-- MariaDB
CREATE DATABASE Katio
COLLATE = `uca1400_spanish_ai_ci`; 
-- Accent Insensitive Case Insensitive

Use Katio;

CREATE TABLE usuarios
(
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(255) NOT NULL,
    Apellido VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Telefono VARCHAR(20) NOT NULL,
    Identificacion VARCHAR(20) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Username VARCHAR (255) NOT NULL,
    INDEX email_idx(Email)
);

CREATE TABLE Authors
(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Lastname NVARCHAR(255) NOT NULL,
    Country NVARCHAR(255) NOT NULL,
    Birthdate DATE NOT NULL,
    INDEX apellido_ix(Lastname)
);

CREATE TABLE Books
(
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    ISBN10 NVARCHAR(255) NOT NULL,
    ISBN13 NVARCHAR(255) NOT NULL,
    Published DATE NOT NULL,
    Edition NVARCHAR(255) NOT NULL,
    Genre NVARCHAR(255) NOT NULL,
    Dewey_Index INT UNSIGNED NOT NULL,
    Author_Id INT UNSIGNED NOT NULL,
    CONSTRAINT `fk_book_author`
        FOREIGN KEY (Author_Id) REFERENCES Authors (Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

CREATE TABLE Narrators
(
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Last_Name NVARCHAR(255) NOT NULL,
    Genre NVARCHAR(255) NOT NULL
);

CREATE TABLE Audiobooks
(
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    ISBN10 NVARCHAR(255) NOT NULL,
    ISBN13 NVARCHAR(255) NOT NULL,
    Published DATE NOT NULL,
    Edition NVARCHAR(255) NOT NULL,
    Genre NVARCHAR(255) NOT NULL,
    Abridged BIT NOT NULL,
    Length_in_seconds INT UNSIGNED NOT NULL,
    Path NVARCHAR(255) NOT NULL,
    Author_Id INT UNSIGNED NOT NULL,
    CONSTRAINT `fk_audiobooks_author`
        FOREIGN KEY (Author_Id) REFERENCES Authors(Id)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
);

CREATE TABLE Genres
(
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL
);


CREATE TABLE Books_Genres
(
  Book_id INT UNSIGNED NOT NULL,
  Genre_Id INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_books_genres_id`
  	FOREIGN KEY (Book_id) REFERENCES Books (Id)
  	ON DELETE CASCADE
  	ON UPDATE RESTRICT,
  CONSTRAINT `fk_genre_books_id`
  	FOREIGN KEY (Genre_Id) REFERENCES Genres (Id)
  	ON DELETE CASCADE
  	ON UPDATE RESTRICT  
);


CREATE TABLE AudioBooks_Authors 
(
  audiobook_id INT UNSIGNED NOT NULL,
  author_id INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_audiobooks_id`
  	FOREIGN KEY (audiobook_id) REFERENCES Audiobooks (Id)
  	ON DELETE CASCADE 
  	ON UPDATE RESTRICT,
  CONSTRAINT `fk_authors_id`
  	FOREIGN KEY (author_id) REFERENCES Authors (ID)
  	ON DELETE CASCADE
  	ON UPDATE RESTRICT 
);

CREATE TABLE BookByBook (
    Id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Id_Book INT UNSIGNED NOT NULL,
    Recommended_Id INT UNSIGNED NOT NULL,

    CONSTRAINT fk_Book
    FOREIGN KEY (Id_Book) REFERENCES Books (Id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,

    CONSTRAINT fk_Recommended
    FOREIGN KEY (Recommended_Id) REFERENCES Books (Id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);